In [1]:
import pandas as pd

In [19]:
crd_csv = "../../Ressources/municipalities_coordinates_newest.csv"
dmg_exl = "../../StormMindData/USDB_1972_2023_ohneSchadenszahlen_ohneBeschriebe.xlsx"
dmg_crd_csv = "../../Ressources/damage_coordinates.csv"

In [32]:
crd = pd.read_csv(crd_csv, encoding="utf-8")
crd

            Municipality   Latitude  Longitude
0        Aeugst am Albis  47.267949   8.486330
1     Affoltern am Albis  47.278247   8.452152
2             Bonstetten  47.315466   8.467060
3        Hausen am Albis  47.243877   8.534235
4               Hedingen  47.298441   8.448975
...                  ...        ...        ...
2754             Rocourt  47.390504   6.956956
2755       Saint-Ursanne  47.364603   7.153949
2756             Seleute  47.366362   7.113219
2757        Vendlincourt  47.451242   7.148502
2758     Sils im Engadin  46.433333   9.766667

[2759 rows x 3 columns]

In [39]:
dmg = pd.read_excel(dmg_exl,skiprows=3)
dmg

,Gemeinde,Gemeindenummer,Weitere Gemeinde,Kanton,Prozessraum,MAXO Datum,Datum,MAXO Zeit,Zeit,Gewässer,...,Gewitter Niederschlagsmenge [mm],Dauerregen Dauer MAXO,Dauerregen Dauer [Std.],Dauerregen Niederschlagsmenge MAXO,Dauerregen Niederschlagsmenge [mm],Schneeschmelze MAXO,Schneeschmelze,Ursache nicht bestimmbar MAXO,Ursache nicht bestimmbar,ID
0,Rossinière,5842,NaN,VD_x001D_,Pont du Lanciau,A,1972-02-17,A,01:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M,1.0,37955
1,Sonvilier,445,NaN,BE_x001D_,NaN,A,1972-03-09,A,01:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M,1.0,37619
2,Ormont-Dessous,5410,NaN,VD_x001D_,NaN,M,1972-04-08,M,20:30:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M,1.0,37956
3,Einsiedeln,1301,NaN,SZ_x001D_,Miesegg,A,1972-05-01,O,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10498
4,Nendaz,6024,NaN,VS_x001D_,Les Follards,M,1972-06-16,O,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M,1.0,37600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28510,Innerthal,1343,NaN,SZ_x001D_,Gugelberg,A,2023-12-17,A,01:30:00,NaN,...,NaN,O,NaN,O,NaN,NaN,NaN,NaN,NaN,39138
28511,Belp,861,Toffen,BE_x001D_,NaN,M,2023-12-18,NaN,NaN,NaN,...,NaN,O,NaN,O,NaN,M,1.0,NaN,NaN,39159
28512,Toffen,884,NaN,BE_x001D_,Breitlohn,M,2023-12-19,M,14:30:00,NaN,...,NaN,O,NaN,O,NaN,NaN,NaN,NaN,NaN,39157
28513,Zollikon,161,NaN,ZH_x001D_,Trichtenhausen,M,2023-12-22,NaN,NaN,NaN,...,NaN,O,NaN,O,NaN,NaN,NaN,NaN,NaN,39201
28514,Tschlin,3753,NaN,GR_x001D_,Vinadi,M,2023-12-23,M,06:00:00,NaN,...,NaN,O,NaN,O,NaN,NaN,NaN,NaN,NaN,39199

In [50]:
import csv
import pandas as pd
for _, row in dmg.iterrows():
    gemeinde = row["Gemeinde"]
    
    match = crd[crd["Municipality"] == gemeinde]

    if not match.empty:
        lat = match.iloc[0]["Latitude"]
        lng = match.iloc[0]["Longitude"]

        xxx = {
            "lat": lat,
            "lng": lng,
            "gemeinde": gemeinde,
            "datum": row["Datum"].strftime('%Y-%m-%d') #pd.to_datetime(dmg["Datum"])
        }

        with open(dmg_crd_csv, mode='a', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=["lat", "lng", "gemeinde", "datum"])
            writer.writerow(xxx)  # oder was du eben damit machen willst